version: '3.8'

services:
  monitoring:
    build: .
    container_name: poshmark
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - shared_network

networks:
  shared_network:
    external: true